try: #The try block lets you test a block of code for errors.
    print(x) #x is not defined

except: #The except block lets you handle the error.
    print("an exception occurred")

#block generated an exception because x is not defined